version: '3.7'

services:
  demo-swagger:
    build: ./demo-swagger
    image: tangjunfeng/my-java
    ports:
      - 18083:18083
    networks:
      - internal_access
      - external_access

  demo-task:
    build: ./demo-task
    image: tangjunfeng/demo-task
    ports:
      - 18089:18089
    networks:
      - internal_access
      - external_access

networks:
  internal_access:
    internal: true
  external_access:

