server:
  port: 18084

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    database: 7
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
