/*
 * This file is generated by jOOQ.
 */
package com.junfeng.demojooq;


import com.junfeng.demojooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooqdemo extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooqdemo</code>
     */
    public static final Jooqdemo JOOQDEMO = new Jooqdemo();

    /**
     * The table <code>jooqdemo.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Jooqdemo() {
        super("jooqdemo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
