/*
 * This file is generated by jOOQ.
 */
package com.junfeng.demojooq;


import com.junfeng.demojooq.tables.User;


/**
 * Convenience access to all tables in jooqdemo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqdemo.user</code>.
     */
    public static final User USER = User.USER;
}
